Hosting & Deployment
UZHBCON/deathnote pull request #5
Opened 2021-04-21 06:20 UTC by julwil

Hey guys,
Hosting a private testnet on heroku isn't really an options since the instances shut down quickly and don't provide persistent storage.. which means every time the instance starts up, we start from scratch.. However, we can use it to host our frontend.

For the BC, we can use Ropsten testnet (an ethereum testnet) to deploy our contracts to. Please have a look at the README in this PR that explains the setup.

2021-04-24 11:51 UTC, kevstre requested changes
Het suscht alles funktioniert be mer, ha chönne de sc of das testnet deploye, esch doch e gueti lösig so, danke!

2021-04-24 11:51 UTC, kevstre commented on Blockchain.Dockerfile
> +RUN npm install truffle-hdwallet-provider
hdWallet provider het be mer ned funktioniert, esch jo au deprecated...

2021-04-24 11:51 UTC, kevstre commented on Blockchain.Dockerfile
> +RUN npm install truffle-hdwallet-provider
```suggestion
RUN npm install @truffle/hdwallet-provider
```

2021-04-25 19:52 UTC, miksut approved these changes
Works fine on my platform. Nice solution.

2021-04-26 06:43 UTC, merged