Multi sig wallet
UZHBCON/deathnote pull request #6
Opened 2021-04-29 17:36 UTC by miksut

Hi guys,
I completed the SC. It now provides functionality to replace beneficiaries and validators. As discussed, these functions require replacing the entire validators/beneficiaries array in order to not mess up and to keep it simpler. Further, each beneficiary needs to claim its own share after the death has finally be confirmed (-> for security reasons). I further added some arguments in the file "Solidity_testing" which can be used to test the SC in Remix. I did some testing and did not run into an error. However, I think it would make sense to test the SC thoroughly at a later stage to be sure to not miss any edge case.

2021-04-30 05:09 UTC, julwil commented
@miksut Looks very nice!

2021-05-01 06:24 UTC, julwil requested changes

2021-05-01 06:24 UTC, julwil commented on contracts/DeathNote.sol
> +pragma solidity ^0.6.0;
I tried to compile it in our dev environment and I got some errors because of the solidity compiler.
When I changed it back to `pragma solidity >=0.4.21 <0.7.0;` it worked

2021-05-02 20:37 UTC, miksut commented on contracts/DeathNote.sol
> +pragma solidity ^0.6.0;
Done, thnx 👍

2021-05-03 12:09 UTC, kevstre commented
@miksut gseht nice us, danke!

2021-05-03 12:13 UTC, kevstre approved these changes

2021-05-06 12:03 UTC, merged